Adds support for full screen snapshots. (#59)
* Adds support for full screen snapshots.

* Removes local screenshots.

* pins auto commit action to reviewed commit

* Puts old screenshot back to kick off CI build.

* Updates api

* Updates continue on failure build step

* Updates tests to support recording screenshots.

* Removes duplicate static resource.

* Fixes up some more tests.

* Updates tests to skip on record.

* Updates build script to handle no png files to remove.

* Adds some disk cleanup to build script to try to fix emulator crashes.

* Updates workflow.

* Reverts setup-gradle cache usage until approved.

* Adjusts emulator architecture.

* 🤖 Updates screenshots

---------

Co-authored-by: rharter <rharter@users.noreply.github.com>

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -74,14 +74,43 @@ jobs:
           path: unit-test-build-reports.zip
 
   instrumentationTests:
-    runs-on: macos-latest
+    runs-on: ubuntu-latest
+    timeout-minutes: 55
     needs: [build]
+
+    permissions:
+      contents: write
+      pull-requests: write
+
     steps:
+      - name: Delete unnecessary tools 🔧
+        run: |
+          echo Remote tool cache
+          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
+
+          echo Remove dotnet runtime
+          sudo rm -rf /usr/share/dotnet || true
+
+          echo Remove haskell runtime
+          sudo rm -rf /opt/ghc || true
+          sudo rm -rf /usr/local/.ghcup || true
+
+          echo Remove swap storage
+          sudo swapoff -a || true
+          sudo rm -f /mnt/swapfile || true
+          free -h
+
+      - name: Enable KVM
+        run: |
+          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
+          sudo udevadm control --reload-rules
+          sudo udevadm trigger --name-match=kvm
+
       - name: Checkout
         uses: actions/checkout@v2
 
       - name: Gradle Wrapper Validation
-        uses: gradle/wrapper-validation-action@v1
+        uses: gradle/wrapper-validation-action@v2
 
       - uses: actions/cache@v3
         with:
@@ -93,13 +122,14 @@ jobs:
             ${{ runner.os }}-gradle
 
       - name: Install JDK 11
-        uses: actions/setup-java@v3
+        uses: actions/setup-java@v4
         with:
           distribution: 'zulu'
           java-version: 11
 
       # Retrieve the cached emulator snapshot.
-      - uses: actions/cache@v3
+      - name: AVD cache
+        uses: actions/cache@v4
         id: avd-cache
         with:
           path: |
@@ -107,21 +137,22 @@ jobs:
             ~/.android/adb*
           key: ${{ runner.os }}-avd-x86_64-pixel_5-31
 
-      - name: Create AVD snapshot
+      - name: Create AVD snapshot for caching
         if: steps.avd-cache.outputs.cache-hit != 'true'
         uses: reactivecircus/android-emulator-runner@v2
         with:
           api-level: 31
           arch: x86_64
           profile: pixel_5
-          disable-animations: false
           force-avd-creation: false
+          disable-animations: false
           ram-size: 4096M
           emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
-          script: echo "Generated AVD snapshot."
+          script: echo "Generated AVD snapshot for caching."
 
       - name: Run instrumentation tests
-        id: instrumentation-tests
+        id: screenshotsverify
+        continue-on-error: true
         uses: reactivecircus/android-emulator-runner@v2
         with:
           api-level: 31
@@ -130,9 +161,47 @@ jobs:
           disable-animations: true
           force-avd-creation: false
           ram-size: 4096M
-          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save
+          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
           # Workaround for https://github.com/ReactiveCircus/android-emulator-runner/issues/319
           script: adb uninstall com.dropbox.dropshots.test; ./gradlew connectedCheck --stacktrace
+
+      - name: Prevent pushing new screenshots if this is a fork
+        id: checkfork_screenshots
+        continue-on-error: false
+        if: steps.screenshotsverify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
+        run: |
+          echo "::error::Screenshot tests failed, please create a PR in your fork first." && exit 1
+
+      - name: Record new screenshots
+        id: screenshotsrecord
+        if: steps.screenshotsverify.outcome == 'failure' && github.event_name == 'pull_request'
+        uses: reactivecircus/android-emulator-runner@v2
+        with:
+          api-level: 31
+          arch: x86_64
+          profile: pixel_5
+          disable-animations: true
+          force-avd-creation: false
+          ram-size: 4096M
+          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
+          # Workaround for https://github.com/ReactiveCircus/android-emulator-runner/issues/319
+          script: adb uninstall com.dropbox.dropshots.test; ./gradlew connectedCheck -Pdropshots.record --stacktrace
+
+      - name: Pull screenshots
+        id: screenshotspull
+        continue-on-error: true
+        if: steps.screenshotsrecord.outcome == 'success' && github.event_name == 'pull_request'
+        run: |
+          rm dropshots/src/androidTest/assets/*.png || true
+          cp dropshots/build/reports/androidTests/dropshots/*.png dropshots/src/androidTest/assets/
+
+      - name: Push new screenshots if available
+        uses: stefanzweifel/git-auto-commit-action@4b8a201e31cadd9829df349894b28c54e6c19fe6
+        if: steps.screenshotspull.outcome == 'success'
+        with:
+          file_pattern: '*/*.png'
+          disable_globbing: true
+          commit_message: "🤖 Updates screenshots"
 
       - name: (Fail-only) Bundle test reports
         if: failure()
@@ -148,7 +217,7 @@ jobs:
   publish:
     runs-on: ubuntu-latest
     if: github.repository == 'dropbox/dropshots' && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
-    needs: [unitTests]
+    needs: [unitTests, instrumentationTests]
     steps:
       - name: Checkout
         uses: actions/checkout@v2
