Adds support for full screen snapshots.

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -76,12 +76,17 @@ jobs:
   instrumentationTests:
     runs-on: macos-latest
     needs: [build]
+
+    permissions:
+      contents: write
+      pull-requests: write
+
     steps:
       - name: Checkout
         uses: actions/checkout@v2
 
       - name: Gradle Wrapper Validation
-        uses: gradle/wrapper-validation-action@v1
+        uses: gradle/wrapper-validation-action@v2
 
       - uses: actions/cache@v3
         with:
@@ -93,7 +98,7 @@ jobs:
             ${{ runner.os }}-gradle
 
       - name: Install JDK 11
-        uses: actions/setup-java@v3
+        uses: actions/setup-java@v4
         with:
           distribution: 'zulu'
           java-version: 11
@@ -121,7 +126,7 @@ jobs:
           script: echo "Generated AVD snapshot."
 
       - name: Run instrumentation tests
-        id: instrumentation-tests
+        id: screenshotsverify
         uses: reactivecircus/android-emulator-runner@v2
         with:
           api-level: 31
@@ -133,6 +138,27 @@ jobs:
           emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save
           # Workaround for https://github.com/ReactiveCircus/android-emulator-runner/issues/319
           script: adb uninstall com.dropbox.dropshots.test; ./gradlew connectedCheck --stacktrace
+
+      - name: Prevent pushing new screenshots if this is a fork
+        id: checkfork_screenshots
+        continue-on-error: false
+        if: steps.screenshotsverify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
+        run: |
+          echo "::error::Screenshot tests failed, please create a PR in your fork first." && exit 1
+
+      - name: Record screenshot tests
+        id: screenshotsrecord
+        if: steps.screenshotsverify.outcome == 'failure' && github.event_name == 'pull_request'
+        run: |
+          cp dropshots/build/reports/androidTests/dropshots/*.png dropshots/src/androidTest/assets/
+
+      - name: Push new screenshots if available
+        uses: stefanzweifel/git-auto-commit-action@v5
+        if: steps.screenshotsrecord.outcome == 'success'
+        with:
+          file_pattern: '*/*.png'
+          disable_globbing: true
+          commit_message: "🤖 Updates screenshots"
 
       - name: (Fail-only) Bundle test reports
         if: failure()
@@ -148,7 +174,7 @@ jobs:
   publish:
     runs-on: ubuntu-latest
     if: github.repository == 'dropbox/dropshots' && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
-    needs: [unitTests]
+    needs: [unitTests, instrumentationTests]
     steps:
       - name: Checkout
         uses: actions/checkout@v2
